name: Jobs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Python version
        run: python --version

name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;
